// Generated by csp.
import plugin0 from '@kieksme/csp-plugin-contact/server';
import plugin1 from '@kieksme/csp-plugin-content/server';
import plugin2 from '@kieksme/csp-plugin-chat/server';
export default [plugin0, plugin1, plugin2];
