// Generated by csp.
import plugin0 from '@kieksme/csp-plugin-contact/browser';
import plugin1 from '@kieksme/csp-plugin-content/browser';
import plugin2 from '@kieksme/csp-plugin-chat/browser';
export default [plugin0, plugin1, plugin2];
