#!/usr/bin/env node
import { readFile, writeFile, mkdir, cp, access, rm } from 'node:fs/promises';
import { resolve, join, dirname } from 'node:path';
import { pathToFileURL } from 'node:url';
import { spawn } from 'node:child_process';
import { realpathSync } from 'node:fs';
import { parse } from 'yaml';
import { validatePlugins, type PluginMeta } from '@kieksme/csp-sdk';
export type Runner = (args: string[], cwd: string) => Promise<void>;
const run: Runner = (args, cwd) =>
  new Promise((ok, fail) => {
    const child = spawn('pnpm', args, { cwd, stdio: 'inherit', shell: false });
    child.once('error', fail);
    child.once('exit', (code) =>
      code === 0 ? ok() : fail(new Error(`pnpm exited ${code}`)),
    );
  });
const registry = 'portal.plugins.json';
const packageName = /^(?:@[a-z0-9][a-z0-9._-]*\/)?[a-z0-9][a-z0-9._-]*$/;
async function readJSON(path: string) {
  return JSON.parse(await readFile(path, 'utf8'));
}
async function readOptional(path: string) {
  try {
    return await readFile(path);
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw err;
  }
}
async function metadata(cwd: string, name: string): Promise<PluginMeta> {
  if (!packageName.test(name)) throw new Error('Invalid package name');
  const pkg = await readJSON(join(cwd, 'node_modules', name, 'package.json'));
  if (
    !pkg.cspPlugin ||
    pkg.cspPlugin.browser !== './browser' ||
    pkg.cspPlugin.server !== './server'
  )
    throw new Error(`${name} is not a CSP plugin with browser/server exports`);
  return pkg.cspPlugin;
}
export async function writeRegistry(cwd: string, names: string[]) {
  if (
    new Set(names).size !== names.length ||
    names.some((n) => !packageName.test(n))
  )
    throw new Error('Invalid registry');
  const metas = await Promise.all(names.map((n) => metadata(cwd, n)));
  validatePlugins(metas);
  await writeFile(join(cwd, registry), JSON.stringify(names, null, 2) + '\n');
  for (const side of ['browser', 'server'])
    await writeFile(
      join(cwd, `portal.${side}.ts`),
      '// Generated by csp. Edit portal.plugins.json through the CLI.\n' +
        names
          .map(
            (n, i) =>
              `import plugin${i} from ${JSON.stringify(n + '/' + side)};`,
          )
          .join('\n') +
        '\nexport default [' +
        names.map((_, i) => 'plugin' + i).join(', ') +
        '];\n',
    );
}
export async function managePlugin(
  command: 'add' | 'remove' | 'list',
  spec: string | undefined,
  cwd = process.cwd(),
  runner: Runner = run,
): Promise<string[]> {
  const names = (await readJSON(join(cwd, registry))) as string[];
  if (!Array.isArray(names)) throw new Error('Expected plugin registry array');
  if (command === 'list') return names;
  if (!spec || spec.startsWith('-') || /[\r\n]/.test(spec))
    throw new Error('Provide a package specification');
  // Customer CLI operates on standalone repos, never a parent workspace lockfile.
  let parent = dirname(cwd);
  while (parent !== dirname(parent)) {
    if (await readOptional(join(parent, 'pnpm-workspace.yaml')))
      throw new Error(
        'Run plugin mutations in a standalone customer repository',
      );
    parent = dirname(parent);
  }
  const ownConfig = await readOptional(join(cwd, 'pnpm-workspace.yaml'));
  if (ownConfig && parse(ownConfig.toString())?.packages?.length)
    throw new Error('Run plugin mutations in a standalone customer repository');
  const files = [
    'package.json',
    'pnpm-lock.yaml',
    'pnpm-workspace.yaml',
    registry,
    'portal.browser.ts',
    'portal.server.ts',
  ];
  const snapshots = await Promise.all(
    files.map((f) => readOptional(join(cwd, f))),
  );
  const before = await readJSON(join(cwd, 'package.json'));
  try {
    if (command === 'add') {
      await runner(['add', '--save-exact', spec], cwd);
      const after = await readJSON(join(cwd, 'package.json'));
      const changed = Object.keys(after.dependencies ?? {}).filter(
        (n) => before.dependencies?.[n] !== after.dependencies[n],
      );
      if (!changed.length) {
        const existing = names.find(
          (n) => spec === n || spec.startsWith(n + '@'),
        );
        if (existing) {
          await writeRegistry(cwd, names);
          return names;
        }
      }
      if (changed.length !== 1)
        throw new Error('Expected one new or updated dependency');
      const next = names.includes(changed[0]) ? names : [...names, changed[0]];
      await writeRegistry(cwd, next);
      return next;
    }
    if (!packageName.test(spec) || !names.includes(spec))
      throw new Error('Plugin is not installed');
    const remaining = names.filter((n) => n !== spec);
    validatePlugins(await Promise.all(remaining.map((n) => metadata(cwd, n))));
    await runner(['remove', spec], cwd);
    await writeRegistry(cwd, remaining);
    return remaining;
  } catch (error) {
    for (let i = 0; i < files.length; i++) {
      if (snapshots[i]) await writeFile(join(cwd, files[i]), snapshots[i]!);
      else await rm(join(cwd, files[i]), { force: true });
    }
    await runner(['install', '--frozen-lockfile'], cwd).catch(() => undefined);
    throw error;
  }
}
export async function main(args = process.argv.slice(2)) {
  if (args[0] === 'init') {
    if (!args[1]) throw new Error('Usage: csp init <empty-directory>');
    const target = resolve(args[1]);
    try {
      await access(target);
      throw new Error('Target already exists');
    } catch (e) {
      if ((e as NodeJS.ErrnoException).code !== 'ENOENT') throw e;
    }
    await mkdir(target, { recursive: true });
    await cp(new URL('../template/', import.meta.url), target, {
      recursive: true,
    });
    console.log(
      `Created ${target}. Copy .env.example to .env, configure providers, then run pnpm install and pnpm build.`,
    );
    return;
  }
  if (
    args[0] !== 'plugin' ||
    !['add', 'remove', 'list'].includes(args[1] ?? '')
  )
    throw new Error(
      'Usage: csp init <directory> | csp plugin add <package> | remove <package-name> | list',
    );
  const names = await managePlugin(
    args[1] as 'add' | 'remove' | 'list',
    args[2],
  );
  console.log(names.join('\n'));
}
if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(realpathSync(resolve(process.argv[1]))).href
)
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  });
