#!/usr/bin/env node
import { readFile, writeFile, mkdir, cp, access, rm } from 'node:fs/promises';
import { resolve, join, dirname } from 'node:path';
import { pathToFileURL } from 'node:url';
import { spawn } from 'node:child_process';
import { realpathSync } from 'node:fs';
import { parse } from 'yaml';
import { validatePlugins, type PluginMeta } from '@kieksme/csp-sdk';
export type Runner = (args: string[], cwd: string) => Promise<void>;
const run: Runner = (args, cwd) =>
  new Promise((ok, fail) => {
    const child = spawn('pnpm', args, { cwd, stdio: 'inherit', shell: false });
    child.once('error', fail);
    child.once('exit', (code) =>
      code === 0 ? ok() : fail(new Error(`pnpm exited ${code}`)),
    );
  });
const registry = 'portal.plugins.json';
const packageName = /^(?:@[a-z0-9][a-z0-9._-]*\/)?[a-z0-9][a-z0-9._-]*$/;
async function readJSON(path: string) {
  return JSON.parse(await readFile(path, 'utf8'));
}
async function readOptional(path: string) {
  try {
    return await readFile(path);
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw err;
  }
}
async function metadata(cwd: string, name: string): Promise<PluginMeta> {
  if (!packageName.test(name)) throw new Error('Invalid package name');
  const pkg = await readJSON(join(cwd, 'node_modules', name, 'package.json'));
  if (
    !pkg.cspPlugin ||
    pkg.cspPlugin.browser !== './browser' ||
    pkg.cspPlugin.server !== './server'
  )
    throw new Error(`${name} is not a CSP plugin with browser/server exports`);
  return pkg.cspPlugin;
}
export async function generateRegistry(
  cwd: string,
  names: string[],
  output?: string,
) {
  if (
    new Set(names).size !== names.length ||
    names.some((n) => !packageName.test(n))
  )
    throw new Error('Invalid registry');
  const manifest = await readJSON(join(cwd, 'package.json'));
  for (const name of names)
    if (!manifest.dependencies?.[name])
      throw new Error(`Plugin ${name} must be declared in dependencies`);
  for (const name of names) {
    const pkg = await readJSON(join(cwd, 'node_modules', name, 'package.json'));
    if (!pkg.exports?.['./browser'] || !pkg.exports?.['./server'])
      throw new Error(`Plugin ${name} must export ./browser and ./server`);
  }
  validatePlugins(await Promise.all(names.map((n) => metadata(cwd, n))));
  if (!output) return;
  await mkdir(output, { recursive: true });
  for (const side of ['browser', 'server'])
    await writeFile(
      join(output, `portal.${side}.ts`),
      '// Generated by csp.\n' +
        names
          .map(
            (n, i) =>
              `import plugin${i} from ${JSON.stringify(n + '/' + side)};`,
          )
          .join('\n') +
        '\nexport default [' +
        names.map((_, i) => 'plugin' + i).join(', ') +
        '];\n',
    );
}
export async function writeRegistry(
  cwd: string,
  names: string[],
  configFile?: string,
) {
  if (configFile) {
    await generateRegistry(cwd, names);
    const profile = await readJSON(configFile);
    profile.plugins = names;
    await writeFile(configFile, JSON.stringify(profile, null, 2) + '\n');
    return;
  }
  // Legacy registry stays supported during migration.
  if (
    new Set(names).size !== names.length ||
    names.some((n) => !packageName.test(n))
  )
    throw new Error('Invalid registry');
  validatePlugins(await Promise.all(names.map((n) => metadata(cwd, n))));
  await writeFile(join(cwd, registry), JSON.stringify(names, null, 2) + '\n');
  for (const side of ['browser', 'server'])
    await writeFile(
      join(cwd, `portal.${side}.ts`),
      '// Generated by csp.\n' +
        names
          .map(
            (n, i) =>
              `import plugin${i} from ${JSON.stringify(n + '/' + side)};`,
          )
          .join('\n') +
        '\nexport default [' +
        names.map((_, i) => 'plugin' + i).join(', ') +
        '];\n',
    );
}
export async function managePlugin(
  command: 'add' | 'remove' | 'list',
  spec: string | undefined,
  cwd = process.cwd(),
  runner: Runner = run,
  configFile?: string,
): Promise<string[]> {
  configFile ??= (await readOptional(join(cwd, 'portal.config.json')))
    ? join(cwd, 'portal.config.json')
    : undefined;
  const names = (
    configFile
      ? (await readJSON(configFile)).plugins
      : await readJSON(join(cwd, registry))
  ) as string[];
  if (!Array.isArray(names)) throw new Error('Expected plugin registry array');
  if (command === 'list') return names;
  if (!spec || spec.startsWith('-') || /[\r\n]/.test(spec))
    throw new Error('Provide a package specification');
  // Customer CLI operates on standalone repos, never a parent workspace lockfile.
  let parent = dirname(cwd);
  while (parent !== dirname(parent)) {
    if (await readOptional(join(parent, 'pnpm-workspace.yaml')))
      throw new Error(
        'Run plugin mutations in a standalone customer repository',
      );
    parent = dirname(parent);
  }
  const ownConfig = await readOptional(join(cwd, 'pnpm-workspace.yaml'));
  if (ownConfig && parse(ownConfig.toString())?.packages?.length)
    throw new Error('Run plugin mutations in a standalone customer repository');
  const files = [
    'package.json',
    'pnpm-lock.yaml',
    'pnpm-workspace.yaml',
    ...(configFile ? [configFile] : [registry]),
    'portal.browser.ts',
    'portal.server.ts',
  ];
  const snapshots = await Promise.all(
    files.map((f) => readOptional(resolve(cwd, f))),
  );
  const before = await readJSON(join(cwd, 'package.json'));
  try {
    if (command === 'add') {
      await runner(['add', '--save-exact', spec], cwd);
      const after = await readJSON(join(cwd, 'package.json'));
      const changed = Object.keys(after.dependencies ?? {}).filter(
        (n) => before.dependencies?.[n] !== after.dependencies[n],
      );
      if (!changed.length) {
        const existing = names.find(
          (n) => spec === n || spec.startsWith(n + '@'),
        );
        if (existing) {
          await writeRegistry(cwd, names, configFile);
          return names;
        }
      }
      if (changed.length !== 1)
        throw new Error('Expected one new or updated dependency');
      const next = names.includes(changed[0]) ? names : [...names, changed[0]];
      await writeRegistry(cwd, next, configFile);
      return next;
    }
    if (!packageName.test(spec) || !names.includes(spec))
      throw new Error('Plugin is not installed');
    const remaining = names.filter((n) => n !== spec);
    validatePlugins(await Promise.all(remaining.map((n) => metadata(cwd, n))));
    await runner(['remove', spec], cwd);
    await writeRegistry(cwd, remaining, configFile);
    return remaining;
  } catch (error) {
    for (let i = 0; i < files.length; i++) {
      if (snapshots[i]) await writeFile(resolve(cwd, files[i]), snapshots[i]!);
      else await rm(resolve(cwd, files[i]), { force: true });
    }
    await runner(['install', '--frozen-lockfile'], cwd).catch(() => undefined);
    throw error;
  }
}
export async function main(args = process.argv.slice(2)) {
  const option = (flag: string) => {
    const i = args.indexOf(flag);
    if (i < 0) return undefined;
    if (!args[i + 1] || args[i + 1].startsWith('--'))
      throw new Error(`Missing value for ${flag}`);
    return args[i + 1];
  };
  const configFile = resolve(
    option('--config') ?? process.env.CSP_CONFIG_PATH ?? 'portal.config.json',
  );
  if (['validate', 'inspect', 'dev', 'build', 'start'].includes(args[0])) {
    const { runPortal } = await import('./runtime.js');
    await runPortal(
      args[0],
      configFile,
      option('--mode') ?? (args[0] === 'dev' ? 'development' : 'production'),
      args.includes('--production'),
    );
    return;
  }
  if (args[0] === 'migrate') {
    try {
      await access(configFile);
      throw new Error('Profile already exists; migration never overwrites it');
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
    }
    const names = await readJSON(join(dirname(configFile), registry));
    await writeFile(
      configFile,
      JSON.stringify(
        {
          schemaVersion: 1,
          id: 'customer',
          branding: { name: 'Service Desk' },
          contact: { phone: '+49 000 000000' },
          contentFile: 'content.json',
          plugins: names,
        },
        null,
        2,
      ) + '\n',
      { flag: 'wx' },
    );
    console.log(
      'Profile created. Existing entrypoints and assets are preserved; validate and compare builds before removing them.',
    );
    return;
  }
  if (args[0] === 'init') {
    if (!args[1]) throw new Error('Usage: csp init <empty-directory>');
    const target = resolve(args[1]);
    try {
      await access(target);
      throw new Error('Target already exists');
    } catch (e) {
      if ((e as NodeJS.ErrnoException).code !== 'ENOENT') throw e;
    }
    await mkdir(target, { recursive: true });
    await cp(new URL('../template/', import.meta.url), target, {
      recursive: true,
    });
    console.log(
      `Created ${target}. Copy .env.example to .env, configure providers, then run pnpm install and pnpm build.`,
    );
    return;
  }
  if (
    args[0] !== 'plugin' ||
    !['add', 'remove', 'list'].includes(args[1] ?? '')
  )
    throw new Error(
      'Usage: csp init <directory> | validate | inspect | dev | build | start | migrate [--config file] | plugin add <package> | remove <package-name> | list',
    );
  const names = await managePlugin(
    args[1] as 'add' | 'remove' | 'list',
    args[2]?.startsWith('--') ? undefined : args[2],
    dirname(configFile),
    run,
    (await readOptional(configFile)) ? configFile : undefined,
  );
  console.log(names.join('\n'));
}
if (
  process.argv[1] &&
  (import.meta.url ===
    pathToFileURL(realpathSync(resolve(process.argv[1]))).href ||
    new URL('./index.js', import.meta.url).href ===
      pathToFileURL(realpathSync(resolve(process.argv[1]))).href)
)
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  });
